x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    MLFLOW_TRACKING_URI: http://mlflow:5000
    MLFLOW_EXPERIMENT_NAME: flowvoyage_pipeline
    AIRFLOW__WEBSERVER__ALLOWED_HOSTS: "*"
    DAGBAG_IMPORT_TIMEOUT: "120"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./modules:/opt/airflow/modules
    - ./requirements.txt:/requirements.txt
    - ./mlruns:/mlflow/mlruns
  depends_on:
    postgres:
      condition: service_started

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname admin --lastname admin --role Admin --email admin@example.com
      "

  airflow-webserver:
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow webserver
      "
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow scheduler
      "

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.10.1
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"