x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.2
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./requirements.txt:/requirements.txt
  depends_on:
    postgres:
      condition: service_started


services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow webserver
      "
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow scheduler
      "

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000